import struct
  import sys
  import os
  import io


  FATEZ_MAGIC = b'\x1bFate/Z\x1b'
  LUA51_MAGIC = b'\x1bLua'

  # Fate/Z type tags -> Standard Lua 5.1 type tags
  FATEZ_NIL = 0x00
  FATEZ_NIL_ALT = 0x03        # alternate nil, no payload
  FATEZ_BOOL = 0x04
  FATEZ_NUMBER = 0x06          # double (8 bytes)
  FATEZ_STRING = 0x07
  FATEZ_INT = 0x0c             # integer (4-byte, extension)

  STD_NIL = 0x00
  STD_BOOL = 0x01
  STD_NUMBER = 0x03
  STD_STRING = 0x04

  # Fate/Z opcode -> Standard Lua 5.1 opcode mapping
  # Derived from reverse engineering liblua.so.5.1.5 (MIPS32 LE)
  # The Fate/Z VM uses a 42-slot opcode table (indices 0-41).
  # Index 0 is invalid. Indices 4, 29, 32 are unused (count=0) but valid.
  # Three comparison opcodes have duplicate FZ indices (5=EQ, 22=LT, 23=LE).
  FZ_TO_STD = {
       1: 36,  # CLOSURE
       2: 20,  # LEN (C field used in FZ, must be cleared)
       3: 25,  # LE
       4: 18,  # UNM (never generated by FZ compiler, count=0)
       5: 23,  # EQ (duplicate of FZ 19)
       6:  1,  # LOADK
       7: 34,  # SETLIST
       8: 30,  # RETURN
       9: 26,  # TEST
      10: 33,  # TFORLOOP
      11: 32,  # FORPREP
      12: 13,  # SUB
      13: 37,  # VARARG
      14: 15,  # DIV
      15: 11,  # SELF
      16: 28,  # CALL
      17:  9,  # SETTABLE
      18:  4,  # GETUPVAL
      19: 23,  # EQ
      20: 24,  # LT
      21: 21,  # CONCAT
      22: 24,  # LT (duplicate of FZ 20)
      23: 25,  # LE (duplicate of FZ 3)
      24:  2,  # LOADBOOL
      25: 16,  # MOD
      26: 31,  # FORLOOP
      27:  6,  # GETTABLE
      28: 10,  # NEWTABLE
      29: 35,  # CLOSE (never generated by FZ compiler, count=0)
      30: 29,  # TAILCALL
      31: 22,  # JMP
      32: 19,  # NOT (never generated by FZ compiler, count=0)
      33: 17,  # POW
      34: 14,  # MUL
      35: 27,  # TESTSET
      36:  0,  # MOVE
      37: 12,  # ADD
      38:  5,  # GETGLOBAL
      39:  8,  # SETUPVAL
      40:  7,  # SETGLOBAL
      41:  3,  # LOADNIL
  }

  # Standard Lua 5.1 opcodes that use iABx format (18-bit Bx field, no C)
  STD_IABX_OPS = {1, 5, 7, 36}  # LOADK, GETGLOBAL, SETGLOBAL, CLOSURE
  # Standard Lua 5.1 opcodes that use iAsBx format (signed 18-bit sBx)
  STD_IASBX_OPS = {22, 31, 32}  # JMP, FORLOOP, FORPREP

  # FZ opcode 2 (LEN) has a non-standard C field that must be cleared
  FZ_LEN_OPCODE = 2


  class FateZReader:
      """Reads Fate/Z bytecode and tracks position."""
      def __init__(self, data):
          self.data = data
          self.off = 0

      def read_byte(self):
          val = self.data[self.off]
          self.off += 1
          return val

      def read_bytes(self, n):
          val = self.data[self.off:self.off + n]
          self.off += n
          return val

      def read_int(self):
          val = struct.unpack_from('<I', self.data, self.off)[0]
          self.off += 4
          return val

      def read_number(self):
          val = self.data[self.off:self.off + 8]
          self.off += 8
          return val

      def read_int4(self):
          val = self.data[self.off:self.off + 4]
          self.off += 4
          return val

      def read_const_string(self):
          size = self.read_int()
          if size == 0:
              return size, None
          enc = self.read_bytes(size)
          return size, enc

      def read_name_string(self):
          size = self.read_int()
          return size

      def remaining(self):
          return len(self.data) - self.off


  class Lua51Writer:
      """Writes standard Lua 5.1 bytecode."""
      def __init__(self, sizeof_size_t=4):
          self.buf = io.BytesIO()
          self.sizeof_size_t = sizeof_size_t

      def write_byte(self, val):
          self.buf.write(bytes([val]))

      def write_bytes(self, data):
          self.buf.write(data)

      def write_int(self, val):
          self.buf.write(struct.pack('<I', val))

      def write_size_t(self, val):
          if self.sizeof_size_t == 8:
              self.buf.write(struct.pack('<Q', val))
          else:
              self.buf.write(struct.pack('<I', val))

      def write_number(self, data):
          self.buf.write(data)

      def write_string(self, size, data):
          self.write_size_t(size)
          if size > 0 and data is not None:
              self.buf.write(data)

      def getvalue(self):
          return self.buf.getvalue()


  def decrypt_string(enc_data):
      if not enc_data:
          return enc_data
      key = enc_data[-1]
      return bytes([b ^ key for b in enc_data])


  def convert_int_to_double(int_bytes):
      val = struct.unpack('<i', int_bytes)[0]
      return struct.pack('<d', float(val))


  def remap_instruction(inst):
      """Remap a Fate/Z instruction to standard Lua 5.1 encoding.

      Lua 5.1 instruction format (32-bit, little-endian):
        iABC:  [B:9][C:9][A:8][Op:6]  (bits 31-23, 22-14, 13-6, 5-0)
        iABx:  [Bx:18][A:8][Op:6]     (bits 31-14, 13-6, 5-0)
        iAsBx: [sBx:18][A:8][Op:6]    (bits 31-14, 13-6, 5-0, sBx = Bx - 131071)

      The opcode is in bits 0-5. We replace it with the standard opcode.
      For LEN (FZ op 2), we also clear the C field (bits 14-22).
      """
      fz_op = inst & 0x3f
      if fz_op == 0 or fz_op not in FZ_TO_STD:
          return inst  # unknown/invalid opcode, pass through

      std_op = FZ_TO_STD[fz_op]

      # Replace opcode field (bits 0-5)
      new_inst = (inst & ~0x3f) | std_op

      # Special handling for LEN -> clear the non-standard C field
      if fz_op == FZ_LEN_OPCODE:
          new_inst = new_inst & ~(0x1ff << 14)

      return new_inst


  def count_upvalues(instructions):
      max_nups = 0
      i = 0
      while i < len(instructions):
          fz_op = instructions[i] & 0x3f
          if fz_op == 1:  # FZ 1 = CLOSURE
              # count following MOVE (FZ 36) and GETUPVAL (FZ 18) pseudo-ops
              nups = 0
              j = i + 1
              while j < len(instructions):
                  next_fz_op = instructions[j] & 0x3f
                  if next_fz_op == 36 or next_fz_op == 18:  # MOVE or GETUPVAL
                      nups += 1
                      j += 1
                  else:
                      break
              max_nups = max(max_nups, nups)
              i = j
          else:
              i += 1
      return max_nups


  def convert_function(reader, writer, depth=0, parent_nups=0):
      """Convert one function prototype from Fate/Z to standard Lua 5.1.

      parent_nups: the number of upvalues this function uses, as inferred
      from post-CLOSURE pseudo-ops in the parent function. Only applies to
      nested functions (depth > 0). For the top-level function, nups is
      typically 0 (or read from the header if non-zero).

      Fate/Z field order (from reverse engineering DumpFunction in liblua.so):
        DumpChar(nups), DumpString(source), DumpChar(numparams),
        DumpInt(linedefined), DumpChar(is_vararg), DumpInt(lastlinedefined),
        DumpChar(maxstacksize), DumpInt(sizecode), DumpBlock(code)

      Standard Lua 5.1 field order:
        DumpString(source), DumpInt(linedefined), DumpInt(lastlinedefined),
        DumpChar(nups), DumpChar(numparams), DumpChar(is_vararg),
        DumpChar(maxstacksize), DumpInt(sizecode), DumpBlock(code)
      """
      nups_raw = reader.read_byte()
      src_size = reader.read_name_string()  # only the size field, no data
      numparams = reader.read_byte()
      linedef = reader.read_int()
      is_vararg = reader.read_byte()
      lastlinedef = reader.read_int()
      maxstack = reader.read_byte()

      # Use inferred nups from parent's CLOSURE pseudo-ops if available,
      # otherwise use the raw value (which may be zeroed in Fate/Z)
      nups = parent_nups if (depth > 0 and nups_raw == 0) else nups_raw

      # Write standard Lua 5.1 fields in their expected order
      writer.write_string(0, None)  # empty source name
      writer.write_int(linedef)
      writer.write_int(lastlinedef)
      writer.write_byte(nups)
      writer.write_byte(numparams)
      writer.write_byte(is_vararg)
      writer.write_byte(maxstack)

      # Code (instructions) - remap Fate/Z opcodes to standard Lua 5.1
      sizecode = reader.read_int()
      writer.write_int(sizecode)
      instructions = []
      for _ in range(sizecode):
          inst = reader.read_int()
          instructions.append(inst)
          writer.write_int(remap_instruction(inst))

      # Constants
      numk = reader.read_int()
      writer.write_int(numk)

      for ci in range(numk):
          t = reader.read_byte()
          base_t = t & 0x7f  # strip high bit for variant types

          if base_t == FATEZ_NIL or base_t == FATEZ_NIL_ALT:
              writer.write_byte(STD_NIL)

          elif base_t == FATEZ_BOOL:
              val = reader.read_byte()
              writer.write_byte(STD_BOOL)
              writer.write_byte(val)

          elif base_t == FATEZ_NUMBER:
              num_data = reader.read_number()
              writer.write_byte(STD_NUMBER)
              writer.write_number(num_data)

          elif base_t == FATEZ_STRING:
              str_size, str_enc = reader.read_const_string()
              str_dec = decrypt_string(str_enc) if str_enc else str_enc
              writer.write_byte(STD_STRING)
              writer.write_string(str_size, str_dec)

          elif base_t == FATEZ_INT:
              int_data = reader.read_int4()
              double_data = convert_int_to_double(int_data)
              writer.write_byte(STD_NUMBER)
              writer.write_number(double_data)

          else:
              raise ValueError(
                  f"Unknown constant type 0x{t:02x} at offset 0x{reader.off - 1:x},
  "
                  f"constant index {ci}, depth {depth}"
              )

      proto_nups = []
      closure_count = 0
      i = 0
      while i < len(instructions):
          fz_op = instructions[i] & 0x3f
          if fz_op == 1:  # FZ 1 = CLOSURE
              nups_for_proto = 0
              j = i + 1
              while j < len(instructions):
                  next_fz_op = instructions[j] & 0x3f
                  if next_fz_op == 36 or next_fz_op == 18:  # MOVE or GETUPVAL
                      nups_for_proto += 1
                      j += 1
                  else:
                      break
              proto_nups.append(nups_for_proto)
              closure_count += 1
              i = j
          else:
              i += 1

      num_protos = reader.read_int()
      writer.write_int(num_protos)
      for pi in range(num_protos):
          inferred_nups = proto_nups[pi] if pi < len(proto_nups) else 0
          convert_function(reader, writer, depth + 1, parent_nups=inferred_nups)

      n_lineinfo = reader.read_int()
      writer.write_int(n_lineinfo)
      for _ in range(n_lineinfo):
          writer.write_int(reader.read_int())

      n_locvars = reader.read_int()
      writer.write_int(n_locvars)
      for _ in range(n_locvars):
          lv_size = reader.read_name_string()  # only reads the size field
          writer.write_string(0, None)
          writer.write_int(reader.read_int())  # startpc
          writer.write_int(reader.read_int())  # endpc

      n_upvalues = reader.read_int()
      writer.write_int(n_upvalues)
      for _ in range(n_upvalues):
          uv_size = reader.read_name_string()  # only reads the size field
          writer.write_string(0, None)


  def deobfuscate(input_data, native=False):
      if input_data[:8] != FATEZ_MAGIC:
          raise ValueError(f"Not a Fate/Z file (magic: {input_data[:8]})")

      reader = FateZReader(input_data)
      reader.off = 16

  sizeof(lua_Number)
      endian = input_data[10]
      sizeof_int = input_data[11]
      sizeof_size_t = input_data[12]
      sizeof_instruction = input_data[13]
      sizeof_number = input_data[14]

      target_sizeof_size_t = struct.calcsize('P') if native else sizeof_size_t

      writer = Lua51Writer(sizeof_size_t=target_sizeof_size_t)
      writer.write_bytes(LUA51_MAGIC)      # \x1bLua (4 bytes)
      writer.write_byte(0x51)               # version 5.1
      writer.write_byte(0x00)               # format version

      writer.write_byte(endian)             # endianness
      writer.write_byte(sizeof_int)         # sizeof(int)
      writer.write_byte(target_sizeof_size_t)  # sizeof(size_t)
      writer.write_byte(sizeof_instruction) # sizeof(Instruction)
      writer.write_byte(sizeof_number)      # sizeof(lua_Number)
      writer.write_byte(0x00)               # integral flag (0 = floating point)

      # Note -> Standard Lua 5.1 does NOT include a LUAC_NUM test number
      # in the bytecode. The 12-byte header is immediately followed by
      # the top-level function prototype.

      # Convert the top-level function
      convert_function(reader, writer)

      if reader.remaining() > 0:
          sys.stderr.write(
              f"Warning: {reader.remaining()} bytes remaining after parse\n"
          )

      return writer.getvalue()


  def extract_strings(input_data):
      if input_data[:8] != FATEZ_MAGIC:
          raise ValueError("Not a Fate/Z file")

      reader = FateZReader(input_data)
      reader.off = 16
      strings = []

      def extract_from_function(depth=0):
          reader.off += 1    # nups
          src_size = reader.read_name_string()  # source name size only
          reader.off += 1    # numparams
          reader.read_int()  # linedef
          reader.off += 1    # is_vararg
          reader.read_int()  # lastlinedef
          reader.off += 1    # maxstacksize

          sizecode = reader.read_int()
          reader.off += sizecode * 4

          numk = reader.read_int()
          for ci in range(numk):
              t = reader.read_byte()
              base_t = t & 0x7f
              if base_t in (FATEZ_NIL, FATEZ_NIL_ALT):
                  pass
              elif base_t == FATEZ_BOOL:
                  reader.off += 1
              elif base_t == FATEZ_NUMBER:
                  reader.off += 8
              elif base_t == FATEZ_STRING:
                  str_size, str_enc = reader.read_const_string()
                  if str_enc:
                      dec = decrypt_string(str_enc)
                      strings.append(('const', dec[:-1].decode('utf-8',
  errors='replace')))
              elif base_t == FATEZ_INT:
                  reader.off += 4
              else:
                  return  # stop on unknown type

          num_protos = reader.read_int()
          for _ in range(num_protos):
              extract_from_function(depth + 1)

          n = reader.read_int()
          reader.off += n * 4
          n = reader.read_int()
          for _ in range(n):
              reader.read_name_string()  # size only
              reader.read_int()  # startpc
              reader.read_int()  # endpc
          n = reader.read_int()
          for _ in range(n):
              reader.read_name_string()  # size only

      try:
          extract_from_function()
      except Exception:
          pass  # best-effort extraction

      return strings


  def process_file(input_path, output_path=None, native=False):
      """Process a single Fate/Z file."""
      with open(input_path, 'rb') as f:
          data = f.read()

      if data[:8] != FATEZ_MAGIC:
          sys.stderr.write(f"Skipping {input_path}: not a Fate/Z file\n")
          return False

      try:
          result = deobfuscate(data, native=native)
          if output_path:
              os.makedirs(os.path.dirname(output_path), exist_ok=True)
              with open(output_path, 'wb') as f:
                  f.write(result)
          return True
      except Exception as e:
          sys.stderr.write(f"Error processing {input_path}: {e}\n")
          return False


  def process_directory(input_dir, output_dir, native=False):
      """Process all Fate/Z files in a directory tree."""
      success = 0
      fail = 0
      skip = 0

      for dirpath, dirnames, filenames in os.walk(input_dir):
          for fname in filenames:
              if not fname.endswith('.lua'):
                  continue
              input_path = os.path.join(dirpath, fname)
              rel_path = os.path.relpath(input_path, input_dir)
              output_path = os.path.join(output_dir, rel_path)

              with open(input_path, 'rb') as f:
                  magic = f.read(8)

              if magic != FATEZ_MAGIC:
                  skip += 1
                  continue

              if process_file(input_path, output_path, native=native):
                  success += 1
                  print(f"  OK: {rel_path}")
              else:
                  fail += 1

      return success, fail, skip


  def main():
      import argparse
      parser = argparse.ArgumentParser(
          description='Deobfuscate Fate/Z Lua bytecode from MiWiFi firmware'
      )
      parser.add_argument('input', help='Input file or directory')
      parser.add_argument('-o', '--output', help='Output file or directory')
      parser.add_argument('--strings', action='store_true',
                         help='Extract and print string constants only')
      parser.add_argument('--batch', action='store_true',
                         help='Process entire directory tree')
      parser.add_argument('--native', action='store_true',
                         help='Output bytecode with host-native sizeof(size_t) '
                              '(needed for 64-bit luadec on 32-bit firmware
  bytecode)')

      args = parser.parse_args()

      if args.strings:
          with open(args.input, 'rb') as f:
              data = f.read()
          strings = extract_strings(data)
          for stype, sval in strings:
              print(f"[{stype}] {sval}")
          return

      if args.batch or os.path.isdir(args.input):
          if not args.output:
              print("Error: --output directory required for batch processing")
              sys.exit(1)
          print(f"Processing directory: {args.input}")
          print(f"Output directory: {args.output}")
          success, fail, skip = process_directory(args.input, args.output,
  native=args.native)
          print(f"\nResults: {success} converted, {fail} failed, {skip} skipped
  (not Fate/Z)")
      else:
          output_path = args.output or args.input + '.dec'
          if process_file(args.input, output_path, native=args.native):
              print(f"Converted: {args.input} -> {output_path}")
          else:
              sys.exit(1)


  if __name__ == '__main__':
      main()
